### PR TITLE
Fix empty last time slot when there are many calendars

### PR DESCRIPTION
**Pull request by adelriosantiago**
This fixes the empty range serialization when selecting the last timeslot and there are more than 1 calendars or many .time-slot classes.

### CODE REVIEW

**Comment by starsirius** [comment]
Thanks, @adelriosantiago. The fix makes sense. A test to cover this would be a bonus!

Can you try to rebase onto master as https://github.com/artsy/day-schedule-selector/pull/33 should fix the build failure on Travis? Also, we added [Danger](https://github.com/danger/danger) so it will complain if you don't change the [CHANGELOG.md](https://github.com/artsy/day-schedule-selector/blob/master/CHANGELOG.md). Feel free to follow the format and add an entry and your name in the "Fixes" section.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/artsy/day-schedule-selector/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by adelriosantiago** [comment]
Hello @starsirius! Here is the updated Pull Request. I also modified the CHANGELOG.md.

Thanks.

**Comment by starsirius** [comment]
@adelriosantiago Almost there! Since it's more like a fix, do you mind moving the changelog entry to be under the "Fixes" section rather than the "Features" section? Thank you! 👍

**Comment by adelriosantiago** [comment]
Done! Thanks!

**Pull request merged**
