### PR TITLE
string days in defaults parameters

### PR DESCRIPTION
**Pull request by pthiers**
Change of the location of the stringdays parameter , to occupy it in the plugin's initialization.

### CODE REVIEW

**Comment by starsirius** [comment]
This looks great. Thanks! It would be awesome if you could help complete the two tests for rendering the [default day labels](https://github.com/artsy/day-schedule-selector/blob/9fb64daa853050afbd66042825146e1ad59719a1/test/index.js#L14) and the [custom day labels](https://github.com/artsy/day-schedule-selector/blob/9fb64daa853050afbd66042825146e1ad59719a1/test/index.js#L33).

We set up the tests with [Karma](http://karma-runner.github.io/), and let me know if anything looks confusing to you. Thanks! :+1:

**Comment by pthiers** [comment]
I've never worked with karma, so I didn't know how to make the tests.

**Comment by starsirius** [comment]
Going to merge this and I will work on the tests. Thanks!

**Comment by starsirius** [comment]
@pthiers FYI https://github.com/artsy/day-schedule-selector/pull/23

**Pull request merged**
