### PR TITLE
Add Danger

### PR DESCRIPTION
**Pull request by starsirius**
1. Add [Danger](https://github.com/danger/danger)
2. Add mocha, chai, and sinon as dev dependencies.

### CODE REVIEW

**Comment by orta** [comment]
Hrm, did I ship a bad build?

**Comment by orta** [comment]
can you try 3.3.1? :)

**Comment by orta** [comment]
The danger side of this is now all good

**Comment by starsirius** [comment]
Included 2 more changes to this PR:

- Update karma-phantomjs-launcher to 1.0.2 and fix the [PhantomJS browser timeout issue](https://github.com/karma-runner/karma-phantomjs-launcher/issues/84#issuecomment-252054603).
- Freeze node version at 6.9.4 to avoid the issue temporarily:
```/home/travis/build/artsy/day-schedule-selector/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/day-schedule-selector/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/artsy/day-schedule-selector/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by starsirius** [comment]
Oh yeah Danger works! Thanks, @orta!

**Pull request merged**
